/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Property, // @ts-ignore
  CondoUnit, // @ts-ignore
  File, // @ts-ignore
  Locker, // @ts-ignore
  ParkingSpot, // @ts-ignore
  Company,
} from "@prisma/client";

export class PropertyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PropertyCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyCountArgs>
  ): Promise<number> {
    return this.prisma.property.count(args);
  }

  async properties<T extends Prisma.PropertyFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyFindManyArgs>
  ): Promise<Property[]> {
    return this.prisma.property.findMany(args);
  }
  async property<T extends Prisma.PropertyFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyFindUniqueArgs>
  ): Promise<Property | null> {
    return this.prisma.property.findUnique(args);
  }
  async createProperty<T extends Prisma.PropertyCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyCreateArgs>
  ): Promise<Property> {
    return this.prisma.property.create<T>(args);
  }
  async updateProperty<T extends Prisma.PropertyUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyUpdateArgs>
  ): Promise<Property> {
    return this.prisma.property.update<T>(args);
  }
  async deleteProperty<T extends Prisma.PropertyDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PropertyDeleteArgs>
  ): Promise<Property> {
    return this.prisma.property.delete(args);
  }

  async findCondoUnits(
    parentId: number,
    args: Prisma.CondoUnitFindManyArgs
  ): Promise<CondoUnit[]> {
    return this.prisma.property
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .condoUnits(args);
  }

  async findFiles(
    parentId: number,
    args: Prisma.FileFindManyArgs
  ): Promise<File[]> {
    return this.prisma.property
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .files(args);
  }

  async findLockers(
    parentId: number,
    args: Prisma.LockerFindManyArgs
  ): Promise<Locker[]> {
    return this.prisma.property
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .Lockers(args);
  }

  async findParkingSpots(
    parentId: number,
    args: Prisma.ParkingSpotFindManyArgs
  ): Promise<ParkingSpot[]> {
    return this.prisma.property
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .ParkingSpots(args);
  }


  async getCompany(parentId: number): Promise<Company | null> {
    return this.prisma.property
        .findUnique({
          where: { id: parentId },
        })
        .company();
  }
}
