const express = require('express')
const router = express.Router()
const { protect } = require('../middleware/authMiddleware')
const {registerUser, login, consoleLog, getUser, modifyUser} = require('../controller/userController')
const {ProfilePictureUpload, ProfilePictureGet} = require('../controller/fileController')
router.route('/')
    .post(registerUser)
    .patch(modifyUser)
router.route('/login')
    .get(login)
router.route('/:userid')
    .get(getUser)
router.route('/file')
    .post(ProfilePictureUpload)
    .get(ProfilePictureGet)
module.exports = router